# Generated by Django 3.2.6 on 2021-08-08 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderplaced',
            old_name='static',
            new_name='status',
        ),
    ]
