# Generated by Django 3.2.6 on 2021-09-12 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_product_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderplaced',
            old_name='product',
            new_name='prodcut',
        ),
    ]
