# Generated by Django 3.2.5 on 2021-09-12 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_rename_product_orderplaced_prodcut'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderplaced',
            old_name='prodcut',
            new_name='product',
        ),
    ]
